// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEaO9DJpJvrkVOOwQvjYvrOAeQgIxdnQo',
    appId: '1:382066512298:web:c4be90b234fa1bb5d9dbd3',
    messagingSenderId: '382066512298',
    projectId: 'himsak-63ae0',
    authDomain: 'himsak-63ae0.firebaseapp.com',
    storageBucket: 'himsak-63ae0.firebasestorage.app',
    measurementId: 'G-MKTC8QS0QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA62u7cpBMOrRD_p0MMBOvyVOHgt_j99Rw',
    appId: '1:382066512298:android:fa1c76d1079b9fcdd9dbd3',
    messagingSenderId: '382066512298',
    projectId: 'himsak-63ae0',
    storageBucket: 'himsak-63ae0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf4dRdWrs1HfWgzui7cHI6oF80lPsVMwM',
    appId: '1:382066512298:ios:87585f403b8b6597d9dbd3',
    messagingSenderId: '382066512298',
    projectId: 'himsak-63ae0',
    storageBucket: 'himsak-63ae0.firebasestorage.app',
    iosBundleId: 'com.example.himsakApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf4dRdWrs1HfWgzui7cHI6oF80lPsVMwM',
    appId: '1:382066512298:ios:87585f403b8b6597d9dbd3',
    messagingSenderId: '382066512298',
    projectId: 'himsak-63ae0',
    storageBucket: 'himsak-63ae0.firebasestorage.app',
    iosBundleId: 'com.example.himsakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEaO9DJpJvrkVOOwQvjYvrOAeQgIxdnQo',
    appId: '1:382066512298:web:6b5ad29b0e7fd678d9dbd3',
    messagingSenderId: '382066512298',
    projectId: 'himsak-63ae0',
    authDomain: 'himsak-63ae0.firebaseapp.com',
    storageBucket: 'himsak-63ae0.firebasestorage.app',
    measurementId: 'G-5HR5WWC7H8',
  );
}
